# Generated by Django 4.2 on 2023-10-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripcion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='maquinaria/')),
                ('categoriaM', models.CharField(choices=[('Cardio', 'Cardio'), ('Pesas', 'Pesas'), ('Maquinas', 'Máquinas'), ('Accesorios', 'Accesorios')], max_length=50, verbose_name='Categoria')),
                ('estado_maquina', models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Reparacion', 'Reparación'), ('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], max_length=50, null=True, verbose_name='Estado de Maquina')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppUsers.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'db_table': 'maquinaria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Reparacion', 'Reparación')], max_length=50, null=True, verbose_name='Tipo')),
                ('detalle', models.CharField(max_length=100, null=True, verbose_name='Detalle')),
                ('fecha_fin', models.DateField(null=True, verbose_name='Fecha final')),
                ('fecha_ini', models.DateField(null=True, verbose_name='Fecha de inicio')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventarioMaquinaria.maquinaria', verbose_name='Maquinaria')),
            ],
            options={
                'verbose_name': 'HistorialMaquinaria',
                'verbose_name_plural': 'HistorialMaquinarias',
                'db_table': 'historialmaquinaria',
                'ordering': ['id'],
            },
        ),
    ]
