# Generated by Django 4.2 on 2023-10-29 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppInventarioMaquinaria', '0001_initial'),
        ('AppUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppUsers.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historialmaquinaria',
            name='maquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventarioMaquinaria.maquinaria', verbose_name='Maquinaria'),
        ),
    ]
