# Generated by Django 4.2 on 2024-01-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ADMINISTRADOR'), (2, 'RECEPCIONISTA'), (4, 'NUTRICIONISTA'), (5, 'ENTRENADOR')], null=True, verbose_name='Rol'),
        ),
    ]
