# Generated by Django 4.2 on 2023-07-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.PositiveIntegerField(blank=True, choices=[('0', 'ADMINISTRADOR'), ('1', 'EMPLEADO')], null=True),
        ),
    ]
