# Generated by Django 4.2 on 2024-01-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0002_alter_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primer_ingreso',
            field=models.BooleanField(default=True),
        ),
    ]
