# Generated by Django 4.2 on 2023-08-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0002_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ADMINISTRADOR'), (2, 'EMPLEADO')], null=True, verbose_name='Rol'),
        ),
    ]
