# Generated by Django 4.2 on 2023-10-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(blank=True, choices=[(1, 'REGULAR'), (2, 'MIEMBRO')], null=True, verbose_name='Tipo')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Total pagado')),
                ('fecha', models.DateField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], null=True, verbose_name='Dia')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Plato/%Y/%m/%d')),
                ('detalle_alimento', models.CharField(max_length=100, null=True, verbose_name='Detalle_Alimento')),
                ('tiempo_comida', models.CharField(max_length=100, null=True, verbose_name='Tiempo_Comida')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
                'db_table': 'dieta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Altura')),
                ('imc', models.CharField(max_length=50, verbose_name='IMC')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'HistorialMiembro',
                'verbose_name_plural': 'HistorialMiembros',
                'db_table': 'historialmiembro',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duracion')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Membresia',
                'verbose_name_plural': 'Membresias',
                'db_table': 'membresia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono')),
                ('direcccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('nombreContact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de contacto')),
                ('telefonoContact', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono de contacto')),
                ('estado_membresia', models.PositiveIntegerField(default=0, verbose_name='Estado membresia')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Miembro/%Y/%m/%d')),
                ('genero', models.PositiveIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], verbose_name='Genero')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('venta_activa', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='venta_activa')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'miembro',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=50, verbose_name='Dia')),
                ('tipo_ejercicio', models.CharField(max_length=50, verbose_name='Tipo_ejercicio')),
                ('links_video', models.CharField(max_length=50, verbose_name='Links_video')),
                ('detalle_ejercicio', models.CharField(max_length=100, null=True, verbose_name='Detalle_Ejercicio')),
                ('recomendacion', models.CharField(max_length=100, null=True, verbose_name='Recomendacion')),
            ],
            options={
                'verbose_name': 'Rutinaejercicio',
                'verbose_name_plural': 'Rutinaejercicios',
                'db_table': 'rutinaejercicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VentaMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total pagado')),
            ],
            options={
                'verbose_name': 'VentaMembresia',
                'verbose_name_plural': 'VentasMembresia',
                'db_table': 'ventaMembresia',
                'ordering': ['id'],
            },
        ),
    ]
