# Generated by Django 4.2 on 2023-08-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(blank=True, choices=[(1, 'REGULAR'), (2, 'MIEMBRO')], null=True, verbose_name='Tipo')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total pagado')),
                ('fecha_asistencia', models.DateField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tarifa', models.PositiveIntegerField(verbose_name='Tarifa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('telefono', models.CharField(max_length=9, null=True, verbose_name='Teléfono')),
                ('direcccion', models.CharField(max_length=100, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('duracion', models.PositiveIntegerField(default=0, verbose_name='Duracion')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Membresia',
                'verbose_name_plural': 'Membresias',
                'db_table': 'membresia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('telefono', models.CharField(max_length=9, null=True, verbose_name='Teléfono')),
                ('direcccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nombreContact', models.CharField(max_length=50, verbose_name='Nombre de contacto')),
                ('telefonoContact', models.CharField(max_length=9, null=True, verbose_name='Teléfono de contacto')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'miembro',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VentaMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total pagado')),
            ],
            options={
                'verbose_name': 'VentaMembresia',
                'verbose_name_plural': 'VentasMembresia',
                'db_table': 'ventaMembresia',
                'ordering': ['id'],
            },
        ),
    ]
