# Generated by Django 4.2 on 2023-10-29 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppControlDeClientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamembresia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='ventamembresia',
            name='membresia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.membresia', verbose_name='Membresia'),
        ),
        migrations.AddField(
            model_name='ventamembresia',
            name='miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.miembro', verbose_name='Miembro'),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.miembro', verbose_name='Miembro'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='historialmiembro',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.miembro', verbose_name='Miembro'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.miembro', verbose_name='Miembro'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.miembro', verbose_name='Miembro'),
        ),
    ]
