# Generated by Django 4.2 on 2023-12-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dieta',
            options={'ordering': ['id'], 'verbose_name': 'dieta', 'verbose_name_plural': 'dietas'},
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='detalle_alimento',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='miembro',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='tiempo_comida',
        ),
        migrations.AddField(
            model_name='dieta',
            name='rango',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1500 kcal'), (2, '2000 kcal'), (3, '2500 kcal'), (4, '3000 kcal'), (5, '3500 kcal'), (6, '4000 kcal'), (7, '4500 kcal')], null=True, verbose_name='rango'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='nombre')),
                ('tiempo', models.PositiveIntegerField(blank=True, choices=[(1, 'Pre desayuno'), (2, 'Desayuno'), (3, 'Refrigerio posdesayuno'), (4, 'Almuerzo'), (5, 'Refrigerio posAlmuerzo'), (6, 'Cena'), (7, 'Refrigerio posCena')], null=True, verbose_name='tiempo')),
                ('detalle', models.CharField(max_length=500, null=True, verbose_name='detalle')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppControlDeClientes.dieta', verbose_name='Dieta')),
            ],
            options={
                'verbose_name': 'comida',
                'verbose_name_plural': 'comidas',
                'db_table': 'comida',
                'ordering': ['id'],
            },
        ),
    ]
