# Generated by Django 4.2 on 2023-09-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmiembro',
            name='miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.miembro', verbose_name='Miembro'),
        ),
    ]
