# Generated by Django 4.2 on 2023-10-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='estado_membresia',
            field=models.PositiveIntegerField(verbose_name='Estado membresia'),
        ),
    ]
