# Generated by Django 4.2 on 2023-10-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0003_alter_miembro_estado_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='venta_activa',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='venta_activa'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_membresia',
            field=models.PositiveIntegerField(default=0, verbose_name='Estado membresia'),
        ),
    ]
