# Generated by Django 4.2 on 2023-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0003_alter_miembro_estado_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='estado_membresia',
            field=models.PositiveIntegerField(default=0, verbose_name='Estado membresia'),
        ),
    ]
