# Generated by Django 4.2 on 2023-12-28 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0003_alter_dieta_options_remove_dieta_detalle_alimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='dieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppControlDeClientes.dieta', verbose_name='Dieta'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='tiempo',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Merienda'), (2, 'Desayuno'), (3, 'Refrigerio de media mañana'), (4, 'Almuerzo'), (5, 'Refrigerio de media tarde'), (6, 'Cena'), (7, 'Refrigerio de noche')], null=True, verbose_name='tiempo'),
        ),
    ]
