# Generated by Django 4.2 on 2024-01-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0004_alter_comida_dieta_alter_comida_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaejercicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Rutina/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='dia',
            field=models.CharField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], max_length=50, verbose_name='Dia'),
        ),
    ]
