# Generated by Django 4.2 on 2023-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0004_miembro_venta_activa_alter_miembro_estado_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='venta_activa',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='venta_activa'),
        ),
    ]
