# Generated by Django 4.2 on 2024-01-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0005_rutinaejercicio_imagen_alter_rutinaejercicio_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(max_length=50, verbose_name='ejercicio')),
                ('intensidad', models.PositiveIntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], null=True, verbose_name='intensidad')),
                ('duracionejer', models.CharField(max_length=50, verbose_name='duracion')),
                ('descanso', models.CharField(max_length=50, verbose_name='descanso')),
            ],
        ),
    ]
