# Generated by Django 4.2 on 2024-01-04 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0006_rutinapersonalizada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutinapersonalizada',
            options={'ordering': ['id'], 'verbose_name': 'rutinapersonalizada', 'verbose_name_plural': 'rutinapersonalizadas'},
        ),
        migrations.AddField(
            model_name='rutinapersonalizada',
            name='rutinaejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppControlDeClientes.rutinaejercicio', verbose_name='RutinaEjercicio'),
        ),
        migrations.AlterModelTable(
            name='rutinapersonalizada',
            table='rutinapersonalizada',
        ),
    ]
