# Generated by Django 4.2 on 2024-01-04 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0007_alter_rutinapersonalizada_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutinaejercicio',
            options={'ordering': ['id'], 'verbose_name': 'rutinaejercicio', 'verbose_name_plural': 'Rutinaejercicios'},
        ),
        migrations.AlterField(
            model_name='rutinapersonalizada',
            name='rutinaejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppControlDeClientes.rutinaejercicio', verbose_name='rutinaEjercicio'),
        ),
    ]
