# Generated by Django 4.2 on 2024-01-09 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0008_alter_rutinaejercicio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDietas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], verbose_name='Dia')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.dieta', verbose_name='Dieta')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.miembro', verbose_name='Miembro')),
            ],
        ),
    ]
