# Generated by Django 4.2 on 2024-01-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0009_listadietas'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadietas',
            name='fecha_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
