# Generated by Django 4.2 on 2024-01-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0010_listadietas_fecha_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listadietas',
            options={'ordering': ['id'], 'verbose_name': 'listadietas', 'verbose_name_plural': 'listasdietas'},
        ),
        migrations.AlterModelTable(
            name='listadietas',
            table='listadietas',
        ),
    ]
