# Generated by Django 4.2 on 2024-01-12 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0011_alter_listadietas_options_alter_listadietas_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Ejercicio/%Y/%m/%d')),
                ('links_video', models.CharField(max_length=50, verbose_name='Links_video')),
                ('musculo', models.PositiveIntegerField(blank=True, choices=[[1, 'Abdomen'], [2, 'Biceps'], [3, 'Espalda'], [4, 'Hombros'], [5, 'Pectorales'], [6, 'Piernas']], verbose_name='Musculo')),
                ('detalle_ejercicio', models.CharField(max_length=100, null=True, verbose_name='Detalle_Ejercicio')),
                ('recomendacion', models.CharField(max_length=100, null=True, verbose_name='Recomendacion')),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
                'db_table': 'ejercicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ListaDeRutinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], verbose_name='Dia')),
                ('fecha_created', models.DateTimeField(auto_now=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.miembro', verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'listarutinas',
                'verbose_name_plural': 'listasrutinas',
                'db_table': 'listarutinas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.PositiveIntegerField(blank=True, choices=[[1, 'Principiante'], [2, 'Intermedio'], [3, 'Avanzado']], null=True, verbose_name='Experiencia')),
                ('tipo_ejercicio', models.PositiveIntegerField(blank=True, choices=[[1, 'Abdomen'], [2, 'Biceps'], [3, 'Espalda'], [4, 'Hombros'], [5, 'Pectorales'], [6, 'Piernas']], null=True, verbose_name='Tipo de ejercicio')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'rutina',
                'verbose_name_plural': 'rutinas',
                'db_table': 'rutina',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='rutinapersonalizada',
            name='rutinaejercicio',
        ),
        migrations.DeleteModel(
            name='RutinaEjercicio',
        ),
        migrations.DeleteModel(
            name='RutinaPersonalizada',
        ),
        migrations.AddField(
            model_name='listaderutinas',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.rutina', verbose_name='Rutina'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppControlDeClientes.rutina', verbose_name='Rutina'),
        ),
    ]
