# Generated by Django 4.2 on 2024-01-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0012_ejercicio_listaderutinas_rutina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='experiencia',
            field=models.PositiveIntegerField(blank=True, choices=[[0, '----------'], [1, 'Principiante'], [2, 'Intermedio'], [3, 'Avanzado']], null=True, verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='tipo_ejercicio',
            field=models.PositiveIntegerField(blank=True, choices=[[0, '----------'], [1, 'Abdomen'], [2, 'Biceps'], [3, 'Espalda'], [4, 'Hombros'], [5, 'Pectorales'], [6, 'Piernas']], null=True, verbose_name='Tipo de ejercicio'),
        ),
    ]
