# Generated by Django 4.2 on 2024-01-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0013_alter_rutina_experiencia_alter_rutina_tipo_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
