# Generated by Django 4.2 on 2024-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppControlDeClientes', '0014_dieta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamembresia',
            name='fecha_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
