# Generated by Django 4.2 on 2023-09-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total de compra')),
                ('fecha_vec', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_compra', models.DateField(auto_now=True)),
                ('fecha_created', models.DateTimeField(auto_now_add=True)),
                ('fecha_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, null=True, verbose_name='Tipo')),
                ('detalle', models.CharField(max_length=100, null=True, verbose_name='Detalle')),
                ('fecha_fin', models.DateField(verbose_name='Fecha final')),
                ('fecha_ini', models.DateField(verbose_name='Fecha de inicio')),
            ],
            options={
                'verbose_name': 'HistorialMaquinaria',
                'verbose_name_plural': 'HistorialMaquinarias',
                'db_table': 'historialmaquinaria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LineaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'LineaVenta',
                'verbose_name_plural': 'LineasVentas',
                'db_table': 'lineaventa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripcion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='maquinaria/')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('estado_maquina', models.CharField(choices=[(1, 'Mantenimiento'), (2, 'Reparacion'), (3, 'Disponible'), (4, 'No Disponible')], max_length=50, null=True, verbose_name='Estado de Maquina')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'db_table': 'maquinaria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripcion')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio de venta')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('fecha_created', models.DateTimeField(auto_now_add=True)),
                ('fecha_updated', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('nivel_bajo', models.PositiveIntegerField(verbose_name='Nivel bajo de producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=9, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('direcccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('fecha_venta', models.DateField(auto_now=True)),
                ('fecha_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'venta',
                'ordering': ['id'],
            },
        ),
    ]
