# Generated by Django 4.2 on 2023-09-06 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppInventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoriaP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppUsers.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.venta', verbose_name='Venta'),
        ),
        migrations.AddField(
            model_name='historialmaquinaria',
            name='maquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.maquinaria', verbose_name='Maquinaria'),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.proveedor', verbose_name='Proveedor'),
        ),
    ]
