# Generated by Django 4.2 on 2023-11-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_vec',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
